### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by chb0github** [chrumck/CtciExercises#1]
How can I test it?

Where are the tests?

**Comment by chrumck** [comment]
The test I ran is here:
https://github.com/chrumck/CtciExercises/blob/master/main.go

I did not make it unit-testable and not write any unit tests though.

Now, your second question is a bit tougher to answer in an easy way. The
thing is not going to run in the online repl I believe. You would need to
install go tools to compile and debug the thing. The other solution is that
I modify the executable so it accepts a command line argument for the
directory path to scan and you just run it like that - compiled.

**Comment by chrumck** [comment]
Yes.

**Comment by chb0github** [comment]
Well,  give me instructions, I want to try

**Comment by chrumck** [comment]
What OS?

**Comment by chb0github** [comment]
ubuntu 16

**Comment by chrumck** [comment]
You need to start by downloading the go tools from here: https://storage.googleapis.com/golang/go1.7.4.linux-amd64.tar.gz

Then you follow the instructions from here: https://golang.org/doc/install#install , which is basically unzipping the file into /usr/local/go, adding the directory to PATH, and then setting up your go workspace as indicated here: https://golang.org/doc/install#testing, which is also just creating a directory to hold the 'go workspace' and setting the GOPATH env variable to point to it. 

After you've done that and confirmed everything works, you can run 'go get github.com/chrumck/CtciExercises' which should pull this repo and compile it.
